package com.spotify.developer.oauth2.enums;

public enum LogType {

    PASS,FAIL,SKIP,INFO,CONSOLE,EXTENTANDCONSOLE,LOGSTACKTRACEINFOINEXTENTREPORT,LOGPRETTYRESPONSETOREPORT,
    LOGPRETTYREQUESTTOREPORT,LOGREQUESTANDRESPONSETOREPORT;
}